### ISSUE TITLE
What about CAT?

### ISSUE THREAD

**Issue by 0xVortex** [mmic-lcl/RGBT-Trakcing-code#2]
Do you plan to share CAT code link?

**Comment by liulei970507** [comment]
The code of CAT and CAT++ are released at https://github.com/liulei970507.

**Comment by 0xVortex** [comment]
Thank you for the information. I also shared your code on [https://github.com/abbasturkoglu/RGB-T-Tracking-Papers-and-Results](https://github.com/abbasturkoglu/RGB-T-Tracking-Papers-and-Results)
